### PR TITLE
feat: allow to mount several external secrets

### LINKED ISSUE #10: [Feat] Allow external secret for secretFiles
https://github.com/project-zot/zot/discussions/1721

### PR DESCRIPTION
**Pull request by loicalbertin**
## Description of changes

added a new `externalSecrets` value. This value is a list of tuples that
defines a "secretName" and a "mountPath". "secretName" references
a secret within the same namespace than the Zot container and
"mountPath" specifies the path within the container filesystem where
the secret is mounted.

Chart version bumped to `0.1.29`.

Fixes #10

I already proposed PR #11 to fix #10, but my personal preference goes to this PR.

To be noted that this PR has 0 impacts on `mountSecret` and `secretFiles` and can be use along with them.

## How to use it

Within `values.yaml`, `externalSecrets` can be speficied this way:

```yaml
externalSecrets:
  - secretName: "secret1"
    mountPath: "/secrets/s1"
  - secretName: "secret2"
    mountPath: "/secrets/s2"
```

A command line flags equivalent would be:

```bash
--set externalSecrets.0.secretName=secret1 --set externalSecrets.0.mountPath=/secrets/s1 --set externalSecrets.1.secretName=secret2 --set externalSecrets.1.mountPath=/secrets/s2
```

### CODE REVIEW

**Comment by rchincha** [comment]
@loicalbertin I like this better, so in future should there be more secrets, there is a way to handle/mount it.

**Comment by rchincha** [comment]
@loicalbertin , PR #14 has been merged, so pls bump up the chart id

**Comment by loicalbertin** [comment]
@rchincha done!

**Review by rchincha — APPROVED** [review]
This PR generalizes https://github.com/project-zot/helm-charts/pull/14 but with a different set of "set" params. 

lgtm.

**Pull request merged**
