### PR TITLE
fix: Added 'httpGet.scheme' to chart values

### PR DESCRIPTION
**Pull request by masoudbahar**
fix: Added 'httpGet.scheme' to support HTTP and HTTPS probes.
docs: Further clarified the use of 'authHeader' value.

### CODE REVIEW

**Review by rchamarthy — APPROVED** [review]

**Comment by andaaron** [comment]
@masoudbahar please update the commit message to start with `fix: `that shold take care of the failed check.

**Comment by masoudbahar** [comment]
Thanks Andrei; I've updated the title.

**Review by Andreea-Lupu — APPROVED** [review]

**Comment by andaaron** [comment]
> Thanks Andrei; I've updated the title.

The title is not enough. The commit message itself needs an update.
The reason for this rule is to make it easier to understand the history when someone uses `git log --oneline`.

**Comment by masoudbahar** [comment]
Sure; please point me to the PR template I should follow and I'll update the PR message accidentally.
Thank you.

**Comment by andaaron** [comment]
> Sure; please point me to the PR template I should follow and I'll update the PR message accidentally. Thank you.

I'm not familiar with what GH offers in terms of creating PRs from the browser.
Locally in the command line you would `git commit --amend -s -S`, and in update the message in editor git opens in the console.

If you're not that familiar with Git we could instead change the message when we `squash and merge` the PR.
Still waiting on the approval from @rchincha right now.

**Comment by masoudbahar** [comment]
I'm familiar with the format; just one question: Do I need to remove the `signed off` by statement, or leave it there

**Comment by andaaron** [comment]
> I'm familiar with the format; just one question: Do I need to remove the `signed off` by statement, or leave it there

Yes
Please keep it. `git commit --amend -s -S` to keep the signoff and also GPG sign.

**Comment by masoudbahar** [comment]
The latest update should pass the CI; I have followed the hints in the job.
If you want me to pull the PR and submit it again, please let me know. 
Thanks

**Comment by andaaron** [comment]
> The latest update should pass the CI; I have followed the hints in the job. If you want me to pull the PR and submit it again, please let me know. Thanks

Did you push the updated commit? I don't see new updates since the PR was opened.

**Comment by masoudbahar** [comment]
I'm back at my desk, and see the message updates I've made. The only options I see right now are commenting, and closing the PR; if you don't see the changes, then I'm okay to close the PR and reissue it with a conventional commits message.

**Comment by rchincha** [comment]
@masoudbahar I believe the commit msg checker is tripping on the multiple "Signed-off" lines. Pls fix and resubmit.

**Comment by masoudbahar** [comment]
Thanks @rchincha, it should be clean now.

**Comment by andaaron** [comment]
I merged. Thank you for your contribution!

**Comment by masoudbahar** [comment]
Thank you for your patience through the back and forth.

**Pull request merged**
